### PR TITLE
refactor: Remove vendor folder

### PR DESCRIPTION
**Pull request by bentenjamin**
Removed vendor folder: Issue [290](https://github.com/noisetorch/NoiseTorch/issues/290)

Tested locally on fresh install
`make dev` builds and runs successfully

Created local private key with `go run scripts/signer.go -g`
`make release` builds, signs and runs successfully

### CODE REVIEW

**Comment by mackshot** [comment]
Removing vendor folder from Repository sounds very reasonable to. Should make all code reviews in future easier. I am not a go guy, thus I cannot tell if there is something special to take into account when removing vendor folders, but in general it is best practice I guess ;)

**Comment by ZyanKLee** [comment]
this PR as is would work. no further steps required. Though the discussion in #284 is not finished yet. There you also can find opinions and reasons for not removing the vendor folder.

**Comment by TheDukeofErl** [comment]
Unless I missed it in the file list, was the vendor folder added to the .gitignore? If not, I believe that's something that we'll want to do to avoid committing the vendor folder back to the repo.

**Comment by aaomidi** [comment]
Why remove the vendor directory? It makes it kinda easier when doing code reviews for getting new dependencies. You can have a CI system that validates the vendor directory hasn't been manually modified.

**Comment by ZyanKLee** [comment]
> Why remove the vendor directory? It makes it kinda easier when doing code reviews for getting new dependencies. You can have a CI system that validates the vendor directory hasn't been manually modified.

Hello, we discussed that matter in #284 - feel free to add your opinion there. I'll wait a few days for it, before going forward with it. So you got a last chance to convince me otherwise 😉

**Comment by aaomidi** [comment]
Thanks for the link, I'll do my best to participate in the discussion soon (out of the country with limited access for a bit). 

Cheers!

**Pull request closed without merging**
