### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by OldiLo**
This have pr #268 and small fixes

### CODE REVIEW

**Comment by ZyanKLee** [comment]
Please do not include other PRs with your small fixes.

**Comment by TheDukeofErl** [comment]
At some point a discussion needs to be had in greater depth over the removal of the vendor folder: https://github.com/noisetorch/NoiseTorch/pull/257 initially set out to do the same thing.

**Comment by ZyanKLee** [comment]
> At some point a discussion needs to be had in greater depth over the removal of the vendor folder: https://github.com/noisetorch/NoiseTorch/pull/257 initially set out to do the same thing. 

Sure, but this is not "small fixes":

**Comment by OldiLo** [comment]
Remove vendor folder, add to .gitignore .vscode .cache noisetorch Fix build with pr #268

**Comment by OldiLo** [comment]
And update go dependencies

**Comment by ZyanKLee** [comment]
My suggestion to go forward is to incorporate your small fix to `c/ladspa/Makefile` into the PR #268, just to handle that change separately from the others.

Your suggestions to add those entries to .gitignore are a no-brainer to me - means: I would merge those separately without batting an eye.

The update to Go dependencies are a bigger issue for me. I will not do this right now; mostly because we did not decide on how to handle the vendor directory going forward. We should have a discussion on that topic. But to have that I would like to wait for a) the review being done and b) for lawl's return (if that happens within a considerable amount of time). He seemed to have a firm stance in those regards and I don't want to just brush that aside.

**Comment by OldiLo** [comment]
I think deleting the vendor folder is a good idea (all malicious code could be stored there).  As for updating dependencies, I think it's also a good idea (there's only nucular, go-glfw, gioui) for bug fixes

**Comment by Dadadah** [comment]
While I agree that deleting the vendor folder is a good idea (hell i made the pr) it's good practice to keep pr's focused on a single issue to make merging things more straight forward.

**Pull request closed without merging**
